### ISSUE TITLE
Possible Links to Include

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/awesome-dspace#1]
@alawvt , here are some ideas that came to my mind for organizing content

## Possible Sections to Add to the Repo
- General Reference for DSpace
- Tutorials
- Feature Reference 
- DSpace Instances with notable features
- Integrations
- Miscellaneous Tools
- Best Practices
  - Developer
  - Repository Admin

## General Reference for DSpace
- [DSpace Support](https://wiki.duraspace.org/display/DSPACE/Support)
- [DSpace Documentation](https://wiki.duraspace.org/display/DSDOC6x/DSpace+6.x+Documentation)
- [DSpace Code](https://github.com/DSpace/DSpace)

**Comment by alawvt** [comment]
Thanks, @terrywbrady, for your help getting started!
